#!/bin/sh
TIME_FILE="/etc/last_known_time"
PIDFILE="/var/run/timekeeper.pid"
UPDATE_INTERVAL_MINUTES=30
SLEEP_SECONDS=$((UPDATE_INTERVAL_MINUTES * 60))


start() {
    echo "Setting time and starting timekeeper..."

    if [ -f "$TIME_FILE" ]; then
        SAVED_TIME=$(cat "$TIME_FILE")
        if [ -n "$SAVED_TIME" ]; then
            echo "Restoring UTC time: $SAVED_TIME"
            date -u -s "$SAVED_TIME"
        fi
    fi

    start-stop-daemon --start --quiet --make-pidfile --pidfile "$PIDFILE" \
      --background --exec /bin/sh -- -c "
        while true; do
            date -u '+%Y-%m-%d %H:%M:%S' > '$TIME_FILE'
            sleep $SLEEP_SECONDS
        done
      "
}

stop() {
    echo "Stopping timekeeper..."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
    rm -f "$PIDFILE"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0